### ISSUE TITLE
Crash on launch with Aureate Reliquary on 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [ZuzAser80/EldritchArcaneWorkings#3]
[Aureate Reliquary](https://mclo.gs/KJcc4Sk)

**Comment by ZuzAser80** [comment]
I need crashlogs, not the mod page, thank you.

**Comment by TalEdd** [comment]
Did you click the link I provide by any chance?

**Comment by ZuzAser80** [comment]
Oh. Right, sorry.

**Comment by ZuzAser80** [comment]
It looks like you included my mod in some big modpack, and errors are not from my mod. But i will look into it in more detail later.

**Comment by TalEdd** [comment]
Its a modified version of Medieval MC Modpack, if that helps in any way

**Comment by ZuzAser80** [comment]
Okay, thank for info.

**Comment by TalEdd** [comment]
Tried out the latest version, that doesn't work also. 😢
https://mclo.gs/hIP4ysj

**Comment by ZuzAser80** [comment]
Just wait. When the third v1.2.0.1 file appears, download it. And test it. Thx

**Comment by TalEdd** [comment]
Unfortunately, same issue again. I think
https://mclo.gs/LjMcfUX

**Comment by cleannrooster** [comment]
Aureate reliquary creator here, you need to change the mixin config file name I think. I changed mine from modid.mixins.json already and tried it with your mod, it seems any errors from now on are on your mod's end.

**Comment by cleannrooster** [comment]
It seems my mod now works with your mod as it was 6 days ago, whatever you did today seems to have made the mixins file unreadable.

**Comment by ZuzAser80** [comment]
Oh. Nice seeing you there. I already have fixed this problem in v1.2.0.2 witch i just uploaded to curse. Yes, i had to change the modid.mixins.json name. Thanks for advice though.

**Comment by TalEdd** [comment]
Alright, it's working now. Finally! 🎉
